spring:
  datasource:
    url: jdbc:mysql://rm-bp1aqaxinsn19f531io.mysql.rds.aliyuncs.com:3306/shuanghu_hr_db?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: shaunghu
    password: ShuangHu_hrms
    driver-class-name: com.mysql.cj.jdbc.Driver